name: AtlidzibasPlugin
version: 1.0
main: lv.side.AtlidzibasPlugin.AtlidzibasPluginMain
api-version: 1.19
commands:
  darbuatlidziba:
    description: Command description here
    usage: /darbuatlidziba